services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file: .env
    user: "1000:996"
    group_add:
      - "996"
    privileged: true
    networks:
      - proxy
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./config/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/SSD:/mnt/SSD:ro
      - /mediavault:/mediavault:ro
      - /NAS2:/NAS2:ro
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEPAGE_ALLOWED_HOSTS=*
      - TZ=Europe/Bucharest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`thebrain.bartis.ro`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.tls.certresolver=cloudflare"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"

  # samba:
  #   image: crazymax/samba:latest
  #   container_name: samba
  #   network_mode: host
  #   restart: unless-stopped
  #   environment:
  #     - TZ=Europe/Bucharest
  #     - SAMBA_LOG_LEVEL=1
  #   volumes:
  #     - /home/alex/docker/samba/config:/data
  #     - /mediavault:/shares/MediaVault
  #     - /NAS2:/shares/NAS2

  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny
    restart: unless-stopped
    privileged: true
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /run/udev:/run/udev:ro
      - ./scrutiny/config:/opt/scrutiny/config
      - ./scrutiny/influxdb:/opt/scrutiny/influxdb
      - /dev:/dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scrutiny.rule=Host(`scrutiny.bartis.ro`)"
      - "traefik.http.routers.scrutiny.entrypoints=websecure"
      - "traefik.http.routers.scrutiny.tls=true"
      - "traefik.http.routers.scrutiny.tls.certresolver=cloudflare"
      - "traefik.http.services.scrutiny.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
