services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file: .env
    user: "1000:996"
    group_add:
      - "996"
    privileged: true
    networks:
      - proxy
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/SSD:/mnt/SSD:ro
      - /mediavault:/mediavault:ro
      - /NAS2:/NAS2:ro
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEPAGE_ALLOWED_HOSTS=*
      - TZ=Europe/Bucharest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`thebrain.lan`)"
      - "traefik.http.routers.homepage.entrypoints=web"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"

  samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    network_mode: host # Samba rămâne pe HOST, nu poate fi pus în proxy
    env_file: .env
    environment:
      - TZ=Europe/Bucharest
      - USERID=1000
      - GROUPID=1000
      - COLLECTOR_CRON="0 */12 * * *"
    volumes:
      - /home/alex/docker/samba/lib:/var/lib/samba
      - /home/alex/docker/samba/cache:/var/cache/samba
      - /home/alex/docker/samba/logs:/var/log/samba
      - /home/alex/docker/samba/config/smb.conf:/etc/samba/smb.conf:ro
      - /mediavault:/shares/"Media Vault"
      - /NAS2:/shares/NAS2
      - /mnt/SSD/movies:/shares/Movies
    tmpfs:
      - /run/samba
    command: -u "${SAMBA_USER};${SAMBA_PASS}"

  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny
    restart: unless-stopped
    privileged: true
    networks:
      - proxy
    ports:
      - 8085:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /run/udev:/run/udev:ro
      - ./scrutiny/config:/opt/scrutiny/config
      - ./scrutiny/influxdb:/opt/scrutiny/influxdb
      - /dev:/dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scrutiny.rule=Host(`scrutiny.lan`)"
      - "traefik.http.routers.scrutiny.entrypoints=web"
      - "traefik.http.services.scrutiny.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
