---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Tools:
    - Google Maps:
      - abbr: Maps
        icon: google-maps.png
        href: https://www.google.com/maps
        description: Maps & Navigation
    - Studio:
      - abbr: Studio
        icon: youtube.png
        href: https://studio.youtube.com
    - Gemini:
      - abbr: Gemini
        icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/gemini-color.png
        href: https://gemini.google.com
    - Github:
        - abbr: GH
          icon: https://github.com/favicon.ico
          href: https://github.com/
    - Docker Hub:
        - abbr: DH
          icon: https://hub.docker.com/favicon.ico
          href: https://hub.docker.com/
    - Tailscale Admin:
        - abbr: TS
          icon: https://tailscale.com/favicon.ico
          href: https://login.tailscale.com/admin/machines
          
- Social:
    - Reddit:
        - abbr: RE
          icon: reddit.png
          href: https://reddit.com/
    - Instagram:
        - abbr: IG
          icon: instagram.png
          href: https://instagram.com/
    - Facebook:
        - abbr: FB
          icon: facebook.png
          href: https://facebook.com/
    - Discord:
        - abbr: DIS
          icon: discord.png
          href: https://discord.com 
- Entertainment:
    - YouTube:
        - abbr: YT
          icon: youtube.png
          href: https://youtube.com/
    - Commafeed:
        - icon: https://www.commafeed.com/favicon.ico
          href: https://www.commafeed.com
- Shopping:
    - Vinted:
        - abbr: VI
          icon: https://www.vinted.ro/favicon.ico
          href: https://vinted.ro
    - Olx:
        - abbr: OLX
          icon: https://www.olx.ro/favicon.ico
          href: https://olx.ro
    - Emag:
        - abbr: EM
          icon: https://www.emag.ro/favicon.ico
          href: https://emag.ro
    - Aliexpress:
        - abbr: ALI 
          icon: https://www.aliexpress.com/favicon.ico
          href: https://aliexpress.com