---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Tools:
    - Google Maps:
      - icon: google-maps.png
        href: https://www.google.com/maps
    - Google Drive:
      - icon: google-drive.png
        href: https://drive.google.com
    - Studio:
      - icon: youtube.png
        href: https://studio.youtube.com
    - Gemini:
      - icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/gemini-color.png
        href: https://gemini.google.com
    - Tailscale Admin:
        - icon: https://tailscale.com/favicon.ico
          href: https://login.tailscale.com/admin/machines
    
- Development:
    - Apple Developer:
        - icon: https://developer.apple.com/assets/elements/icons/xcode-s-dark/xcode-s-dark-256x256_2x.png
          href: https://developer.apple.com
    - Docker Hub:
        - icon: https://hub.docker.com/favicon.ico
          href: https://hub.docker.com/
    - Github:
        - icon: https://github.com/favicon.ico
          href: https://github.com/

- Social:
    - Reddit:
        - abbr: RE
          icon: reddit.png
          href: https://reddit.com/
    - Instagram:
        - abbr: IG
          icon: instagram.png
          href: https://instagram.com/
    - Facebook:
        - abbr: FB
          icon: facebook.png
          href: https://facebook.com/
    - Discord:
        - abbr: DIS
          icon: discord.png
          href: https://discord.com 
- Entertainment:
    - YouTube:
        - abbr: YT
          icon: youtube.png
          href: https://youtube.com/
- Shopping:
    - Vinted:
        - abbr: VI
          icon: https://www.vinted.ro/favicon.ico
          href: https://vinted.ro
    - Olx:
        - abbr: OLX
          icon: https://www.olx.ro/favicon.ico
          href: https://olx.ro
    - Emag:
        - abbr: EM
          icon: https://www.emag.ro/favicon.ico
          href: https://emag.ro
    - Aliexpress:
        - abbr: ALI 
          icon: https://www.aliexpress.com/favicon.ico
          href: https://aliexpress.com
- Lifestyle:
    - MyFitnessPal:
        - abbr: MFP
          icon: https://www.myfitnesspal.com/favicons/apple-touch-icon.png?v=1
          href: https://www.myfitnesspal.com/