- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8096
        server: my-docker
        container: jellyfin
        description: Media Server
        widget:
          type: jellyfin
          url: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8096
          key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
          enableBlocks: true
          enableNowPlaying: true
    - Plex:
        icon: plex.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:32400/web
        server: my-docker
        container: plex
        widget:
          type: plex
          url: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:32400
          key: {{HOMEPAGE_VAR_PLEX_KEY}}
    - Audiobookshelf:
        icon: audiobookshelf.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8089
        server: my-docker
        container: audiobookshelf
        widget:
          type: audiobookshelf
          url: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8089
          key: {{HOMEPAGE_VAR_ABS_KEY}}

- Downloads:
    - Transmission:
        icon: transmission.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:9091
        server: my-docker
        container: transmission
        description: Torrent Client
        widget:
          type: transmission
          url: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:9091
          username: {{HOMEPAGE_VAR_TRANSMISSION_USER}}
          password: {{HOMEPAGE_VAR_TRANSMISSION_PASS}}
    - Radarr:
        icon: radarr.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:7878
        server: my-docker
        container: radarr
        widget:
          type: radarr
          url: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:7878
          key: {{HOMEPAGE_VAR_RADARR_KEY}}
    - SickChill:
        icon: sickchill.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8081
        server: my-docker
        container: sickchill
    - LazyLibrarian:
        icon: lazylibrarian.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:5299
        server: my-docker
        container: lazylibrarian

- System:
    - Portainer:
        icon: portainer.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:9000
        server: my-docker
        container: portainer
        widget:
          type: portainer
          url: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:9000
          env: 3
          key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
    - Scrutiny:
        icon: scrutiny.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8085
        description: Drive Health
        server: my-docker
        container: scrutiny
        widget:
          type: scrutiny
          url: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8085
    - Glances:
        icon: glances.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:61208
        server: my-docker
        container: glances
        widget:
          type: glances
          url: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:61208
          metric: disk
    - iLO Management:
        icon: hp.png
        href: {{HOMEPAGE_VAR_ILO_IP}}
        siteMonitor: {{HOMEPAGE_VAR_ILO_IP}}
    - Watchtower:
        icon: watchtower.png
        server: my-docker
        container: watchtower
- Network:
    - Speedtest:
        icon: speedtest-tracker.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8083
        server: my-docker
        container: speedtest-tracker
        widget:
          type: speedtest
          url: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8083
    - AdGuard:
        icon: adguard-home.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8084
        server: my-docker
        container: adguard
        widget:
          type: adguard
          url: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8084
          username: {{HOMEPAGE_VAR_ADGUARD_USER}}
          password: {{HOMEPAGE_VAR_ADGUARD_PASS}}
    - Homebridge:
        icon: homebridge.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8581
        server: my-docker
        container: homebridge
        widget:
          type: homebridge
          url: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8581
          username: {{HOMEPAGE_VAR_HOMEBRIDGE_USER}}
          password: {{HOMEPAGE_VAR_HOMEBRIDGE_PASS}}
    - Router TP-Link:
        icon: tp-link.png
        href: {{HOMEPAGE_VAR_TPLINKROUTER}}
        siteMonitor: {{HOMEPAGE_VAR_TPLINKROUTER}}
    - Router Asus:
        icon: asus.png
        href: {{HOMEPAGE_VAR_ASUSROUTER}}
        siteMonitor: {{HOMEPAGE_VAR_ASUSROUTER}}
- Office & Tools:
    - Stirling-PDF:
        icon: stirling-pdf.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8086
        server: my-docker
        container: stirling-pdf
    - FileBrowser:
        icon: filebrowser.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8082
        server: my-docker
        container: filebrowser
    - Duplicati:
        icon: duplicati.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8200
        server: my-docker
        container: duplicati
    - Gmail (Bichon):
        icon: si-gmail
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:15630
        description: Local Gmail Backup
        server: my-docker
        container: bichon
    - HandBrake:
        icon: handbrake.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:5800
        description: Transcodare Video H.265
        server: my-docker
        container: handbreak
