- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://jellyfin.lan
        server: my-docker
        container: jellyfin
        description: Media Server
        widget:
          type: jellyfin
          url: http://jellyfin:8096
          key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
          enableBlocks: true
          enableNowPlaying: true
    - Plex:
        icon: plex.png
        href: http://plex.lan
        server: my-docker
        container: plex
        widget:
          type: plex
          url: http://plex:32400
          key: {{HOMEPAGE_VAR_PLEX_KEY}}
    - Audiobookshelf:
        icon: audiobookshelf.png
        href: http://audiobookshelf.lan
        server: my-docker
        container: audiobookshelf
        widget:
          type: audiobookshelf
          url: http://audiobookshelf
          key: {{HOMEPAGE_VAR_ABS_KEY}}
    - Romm:
       icon: romm.png
       href: http://roms.lan
       server: my-docker
       container: romm
       widget:
          type: romm
          url: http://roms.lan
          fields: ["platforms", "totalRoms", "saves", "states"]

- Downloads:
    - Transmission:
        icon: transmission.png
        href: http://transmission.lan
        server: my-docker
        container: transmission
        description: Torrent Client
        widget:
          type: transmission
          url: http://transmission.lan:9091
          username: {{HOMEPAGE_VAR_TRANSMISSION_USER}}
          password: {{HOMEPAGE_VAR_TRANSMISSION_PASS}}
    - Radarr:
        icon: radarr.png
        href: http://radarr.lan
        server: my-docker
        container: radarr
        widget:
          type: radarr
          url: http://radarr:7878
          key: {{HOMEPAGE_VAR_RADARR_KEY}}
    - SickChill:
        icon: sickchill.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8081
        server: my-docker
        container: sickchill
    - LazyLibrarian:
        icon: lazylibrarian.png
        href: http://lazylibrarian.lan
        server: my-docker
        container: lazylibrarian

- System:
    - Portainer:
        icon: portainer.png
        href: http://portainer.lan
        server: my-docker
        container: portainer
        widget:
          type: portainer
          url: http://portainer:9000
          env: 3
          key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
    - Scrutiny:
        icon: scrutiny.png
        href: http://scrutiny.lan
        description: Drive Health
        server: my-docker
        container: scrutiny
        widget:
          type: scrutiny
          url: http://scrutiny:8080
    - Glances:
        icon: glances.png
        href: http://glances.lan
        server: my-docker
        container: glances
        widget:
          type: glances
          url: http://glances:61208
          metric: disk
    - Duplicati:
        icon: duplicati.png
        href: http://duplicati.lan
        server: my-docker
        container: duplicati
    - iLO Management:
        icon: hp.png
        href: {{HOMEPAGE_VAR_ILO_IP}}
        siteMonitor: {{HOMEPAGE_VAR_ILO_IP}}
    - Tugtainer:
        icon: tugtainer.png
        href: http://tugtainer.lan
        server: my-docker
        container: tugtainer
- Network:
    - Speedtest:
        icon: speedtest-tracker.png
        href: http://speedtest.lan
        server: my-docker
        container: speedtest-tracker
        widget:
          type: speedtest
          url: http://speedtest-tracker:80
    - AdGuard:
        icon: adguard-home.png
        href: http://adguard.lan
        server: my-docker
        container: adguard
        widget:
          type: adguard
          url: http://adguard
          username: {{HOMEPAGE_VAR_ADGUARD_USER}}
          password: {{HOMEPAGE_VAR_ADGUARD_PASS}}
    - Homebridge:
        icon: homebridge.png
        href: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8581
        server: my-docker
        container: homebridge
        widget:
          type: homebridge
          url: http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8581
          username: {{HOMEPAGE_VAR_HOMEBRIDGE_USER}}
          password: {{HOMEPAGE_VAR_HOMEBRIDGE_PASS}}
    - Traefik:
       icon: traefik.png
       href: http://traefik.lan
       server: my-docker
       container: traefik
       widget:
          type: traefik
          url: http://traefik:8080
    - Proxmox:
        icon: proxmox
        href: https://proxmox.lan
        siteMonitor: https://proxmox.lan
        widget:
            type: proxmox
            url: https://proxmox.lan
            username: {{HOMEPAGE_VAR_PROXMOX_TOKEN_ID}}
            password: {{HOMEPAGE_VAR_PROXMOX_TOKEN_PASSWORD}}
    - PorTracker:
        icon: mdi-lan-check
        href: http://portracker.lan
        description: Open Port Monitor
        server: my-docker
        container: portracker
    - Router TP-Link:
        icon: tp-link.png
        href: {{HOMEPAGE_VAR_TPLINKROUTER}}
        siteMonitor: {{HOMEPAGE_VAR_TPLINKROUTER}}
    - Router Asus:
        icon: asus.png
        href: {{HOMEPAGE_VAR_ASUSROUTER}}
        siteMonitor: {{HOMEPAGE_VAR_ASUSROUTER}}
- Office & Tools:
    - Stirling-PDF:
        icon: stirling-pdf.png
        href: http://stirling.lan
        server: my-docker
        container: stirling-pdf
    - FileBrowser:
        icon: filebrowser.png
        href: http://filebrowser.lan
        server: my-docker
        container: filebrowser
    - Paperless:
        tab: Main
        icon: paperless-ngx.png
        href: http://paperless.lan
        description: Bill/Receipt Management & OCR
        server: my-docker
        container: paperless-ngx
        widget:
          type: paperlessngx
          url: http://paperless-ngx:8000/
          key: "{{HOMEPAGE_VAR_PAPERLESS_TOKEN}}"
    - Bichon:
        icon: si-gmail
        href: http://bichon.lan
        description: Local Gmail Backup
        server: my-docker
        container: bichon
    - HandBrake:
        icon: handbrake.png
        href: http://handbrake.lan
        description: Transcodare Video H.265
        server: my-docker
        container: handbrake
