- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        server: my-docker
        container: jellyfin
        description: Media Server Main
        useEqualHeights: true
        widget:
          type: jellyfin
          url: "http://jellyfin:8096"
          key: "{{HOMEPAGE_VAR_JELLYFIN_KEY}}"
          enableBlocks: true
          enableNowPlaying: true
    - Plex:
        icon: plex.png
        href: "{{HOMEPAGE_VAR_PLEX_URL}}"
        server: my-docker
        container: plex
        description: Media Server Backup
        useEqualHeights: true
        widget:
          type: plex
          url: "http://plex:32400"
          key: "{{HOMEPAGE_VAR_PLEX_KEY}}"
    - Audiobookshelf:
        icon: audiobookshelf.png
        href: "{{HOMEPAGE_VAR_AUDIOBOOKSHELF_URL}}"
        server: my-docker
        container: audiobookshelf
        description: Audio Books Server
        useEqualHeights: true
        widget:
          type: audiobookshelf
          url: "http://audiobookshelf:80"
          key: "{{HOMEPAGE_VAR_ABS_KEY}}"
    - Immich:
        icon: immich.png
        href: "{{HOMEPAGE_VAR_IMMICH_URL}}"
        server: my-docker
        container: immich_server
        description: Photo Collection
        useEqualHeights: true
        widget:
          type: immich
          url: "http://immich-server:2283"
          key: "{{HOMEPAGE_VAR_IMMICH_KEY}}"
          version: 2
    - Romm:
        icon: romm.png
        href: "{{HOMEPAGE_VAR_ROMS_URL}}"
        server: my-docker
        container: romm
        description: Old Games Emulator
        useEqualHeights: true
        widget:
          type: romm
          url: "http://romm:8080"
          fields: ["platforms", "totalRoms", "saves", "states"]

- Downloads:
    - Transmission:
        icon: transmission.png
        href: "{{HOMEPAGE_VAR_TRANSMISSION_URL}}"
        server: my-docker
        container: transmission
        description: Torrent Client
        useEqualHeights: true
        widget:
          type: transmission
          url: "http://transmission:9091"
          username: "{{HOMEPAGE_VAR_TRANSMISSION_USER}}"
          password: "{{HOMEPAGE_VAR_TRANSMISSION_PASS}}"
    - Radarr:
        icon: radarr.png
        href: "{{HOMEPAGE_VAR_RADARR_URL}}"
        server: my-docker
        container: radarr
        description: Find Movies
        useEqualHeights: true
        widget:
          type: radarr
          url: "http://radarr:7878"
          key: "{{HOMEPAGE_VAR_RADARR_KEY}}"
    - Sonarr:
        icon: sonarr.png
        href: "{{HOMEPAGE_VAR_SONARR_URL}}"
        server: my-docker
        container: sonarr
        description: Find TVShows
        useEqualHeights: true
        widget:
          type: sonarr
          url: "http://sonarr:8989"
          key: "{{HOMEPAGE_VAR_SONARR_KEY}}"
    - Prowlarr:
        icon: prowlarr.png
        href: "{{HOMEPAGE_VAR_PROWLARR_URL}}"
        server: my-docker
        container: prowlarr
        useEqualHeights: true
        widget:
          type: prowlarr
          url: "{{HOMEPAGE_VAR_PROWLARR_URL}}"
          key: "{{HOMEPAGE_VAR_PROWLARR_KEY}}"
    - LazyLibrarian:
        icon: lazylibrarian.png
        href: "{{HOMEPAGE_VAR_LAZYLIBRARIAN_URL}}"
        server: my-docker
        container: lazylibrarian
        description: Find Books
        useEqualHeights: true

- System:
    - Portainer:
        icon: portainer.png
        href: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
        server: my-docker
        container: portainer
        useEqualHeights: true
        widget:
          type: portainer
          url: "http://portainer:9000"
          env: 3
          key: "{{HOMEPAGE_VAR_PORTAINER_KEY}}"
    - Kopia:
        icon: kopia.png
        description: Photo Archive Backup
        href: "{{HOMEPAGE_VAR_KOPIA_URL}}"
        server: my-docker
        container: kopia
        useEqualHeights: true
        widget:
            type: kopia
            url: "http://kopia:5115"
            username: "{{HOMEPAGE_VAR_KOPIA_USERNAME}}"
            password: "{{HOMEPAGE_VAR_KOPIA_PASS}}"
    - Tugtainer:
        icon: tugtainer.png
        href: "{{HOMEPAGE_VAR_TUGTAINER_URL}}"
        server: my-docker
        container: tugtainer
        useEqualHeights: true
        widget:
          type: customapi
          url: "http://tugtainer:80/api/public/summary"
          method: GET
          mappings:
            - field: "0.by_update_available.true"
              label: "Updates Available"
              format: number
    - Proxmox:
        icon: proxmox
        href: "https://proxmox.lan"
        siteMonitor: "https://proxmox.lan"
        useEqualHeights: true
        widget:
            type: proxmox
            url: "https://proxmox.lan"
            hideErrors: true
            username: "{{HOMEPAGE_VAR_PROXMOX_TOKEN_ID}}"
            password: "{{HOMEPAGE_VAR_PROXMOX_TOKEN_PASSWORD}}"
    - Duplicati:
        icon: duplicati.png
        href: "{{HOMEPAGE_VAR_DUPLICATI_URL}}"
        server: my-docker
        container: duplicati
        useEqualHeights: true
    - iLO Management:
        icon: hp.png
        href: "{{HOMEPAGE_VAR_ILO_IP}}"
        siteMonitor: "{{HOMEPAGE_VAR_ILO_IP}}"
        useEqualHeights: true

- Network:
    - Speedtest:
        icon: speedtest-tracker.png
        href: "{{HOMEPAGE_VAR_SPEEDTEST_URL}}"
        server: my-docker
        container: speedtest-tracker
        useEqualHeights: true
        widget:
          type: speedtest
          url: "http://speedtest-tracker:80"
    - Homebridge:
        icon: homebridge.png
        href: "http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8581"
        server: my-docker
        container: homebridge
        useEqualHeights: true
        widget:
          type: homebridge
          url: "http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8581"
          username: "{{HOMEPAGE_VAR_HOMEBRIDGE_USER}}"
          password: "{{HOMEPAGE_VAR_HOMEBRIDGE_PASS}}"
    - Traefik:
        icon: traefik.png
        href: "{{HOMEPAGE_VAR_TRAEFIK_URL}}"
        server: my-docker
        container: traefik
        useEqualHeights: true
        widget:
          type: traefik
          url: "http://traefik:8080"
    - AdGuard:
        icon: adguard-home.png
        href: "{{HOMEPAGE_VAR_ADGUARD_URL}}"
        server: my-docker
        container: adguard
        useEqualHeights: true
        widget:
          type: adguard
          url: "http://adguard"
          username: "{{HOMEPAGE_VAR_ADGUARD_USER}}"
          password: "{{HOMEPAGE_VAR_ADGUARD_PASS}}"
    - AdGuard TheSpine:
        icon: adguard-home.png
        href: "http://{{HOMEPAGE_VAR_ADGUARD_SPINE_IP}}:8080"
        siteMonitor: "http://{{HOMEPAGE_VAR_ADGUARD_SPINE_IP}}:8080"
        useEqualHeights: true
        widget:
          type: adguard
          url: "http://{{HOMEPAGE_VAR_ADGUARD_SPINE_IP}}:8080"
          username: "{{HOMEPAGE_VAR_ADGUARD_SPINE_USER}}"
          password: "{{HOMEPAGE_VAR_ADGUARD_SPINE_PASS}}"
    - OpenWRT:
        icon: openwrt.png
        description: GL.iNet Router
        href: "{{HOMEPAGE_VAR_ROUTER}}"
        siteMonitor: "{{HOMEPAGE_VAR_ROUTER}}"
        useEqualHeights: true

- Monitoring:
    - Scrutiny:
        icon: scrutiny.png
        href: "{{HOMEPAGE_VAR_SCRUTINY_URL}}"
        description: Drive Health
        server: my-docker
        container: scrutiny
        useEqualHeights: true
        widget:
          type: scrutiny
          url: "http://scrutiny:8080"
    - Glances CPU:
        icon: glances.png
        href: "{{HOMEPAGE_VAR_GLANCES_URL}}"
        server: my-docker
        container: glances
        useEqualHeights: true
        widget:
          type: glances
          url: "http://glances:61208"
          version: 4
          metric: cpu
          refreshInterval: 5000
          pointsLimit: 15
    - WatchYourLAN:
        icon: watchyourlan.png
        href: "{{HOMEPAGE_VAR_WYL_URL}}"
        description: Network Scanner
        server: my-docker
        container: watchyourlan
        useEqualHeights: true
        widget:
          type: customapi
          url: "http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8840/api/status"
          refreshInterval: 30000
          method: GET
          display: block
          mappings:
            - field: Online
              label: Online
              format: number
            - field: Known
              label: Known
              format: number
            - field: Unknown
              label: Unknown
              format: number
            - field: Total
              label: Total
              format: number
    - Uptime Kuma:
        icon: uptime-kuma
        href: "http://{{HOMEPAGE_VAR_ADGUARD_SPINE_IP}}:3001"
        description: Server Monitoring
        siteMonitor: "http://{{HOMEPAGE_VAR_ADGUARD_SPINE_IP}}:3001"
        useEqualHeights: true
        widget:
          type: uptimekuma
          url: "http://{{HOMEPAGE_VAR_ADGUARD_SPINE_IP}}:3001"
          slug: alexhomelab
    - Homelab Power Usage:
        icon: home-assistant.png
        href: "{{HOMEPAGE_VAR_HASS_URL}}"
        useEqualHeights: true
        widget:
          type: homeassistant
          url: "http://{{HOMEPAGE_VAR_INTERNAL_IP}}:8123"
          key: "{{HOMEPAGE_VAR_HASS_KEY}}"
          container: homeassistant
          entity: sensor.smart_plug_mini_power
          custom:
          - state: sensor.smart_plug_mini_power
            label: Power
          - state: sensor.actual_monthly_homelab_cost
            label: "Current Price"
            unit: " RON"
          - state: sensor.estimated_monthly_energy_cost
            label: "Monthly Estimate"
            unit: " RON"
    - PorTracker:
        icon: mdi-lan-check
        href: "{{HOMEPAGE_VAR_PORTRACKER_URL}}"
        useEqualHeights: true
        server: my-docker
        container: portracker
    - Dozzle:
        icon: dozzle
        href: "{{HOMEPAGE_VAR_DOZZLE_URL}}"
        useEqualHeights: true
        server: my-docker
        container: dozzle

- Office & Tools:
    - Stirling-PDF:
        icon: stirling-pdf.png
        href: "{{HOMEPAGE_VAR_STIRLING_URL}}"
        server: my-docker
        container: stirling-pdf
        description: PDF Editor
        useEqualHeights: true
    - FileBrowser:
        icon: filebrowser.png
        href: "{{HOMEPAGE_VAR_FILEBROWSER_URL}}"
        server: my-docker
        container: filebrowser
        description: File Browser
        useEqualHeights: true
    - Bichon:
        icon: si-gmail
        href: "{{HOMEPAGE_VAR_BICHON_URL}}"
        description: Local Gmail Backup
        useEqualHeights: true
        server: my-docker
        container: bichon
    - Paperless:
        icon: paperless-ngx.png
        href: "{{HOMEPAGE_VAR_PAPERLESS_URL}}"
        description: Bill/Receipt Management & OCR
        useEqualHeights: true
        server: my-docker
        container: paperless-ngx
        widget:
          type: paperlessngx
          url: "http://paperless-ngx:8000"
          key: "{{HOMEPAGE_VAR_PAPERLESS_TOKEN}}"

- Dev Stuff:
    - IT Tools:
        icon: it-tools.png
        href: "{{HOMEPAGE_VAR_ITTOOLS_URL}}"
        server: my-docker
        container: it-tools
        useEqualHeights: true
    - VSCode:
        icon: vscode.png
        href: "{{HOMEPAGE_VAR_CODESERVER_URL}}"
        server: my-docker
        container: it-tools
        useEqualHeights: true
        
- The Dorna:
    - Proxmox Dorna:
        icon: proxmox.png
        href: "https://{{HOMEPAGE_VAR_THEDORNA_PROXMOX}}"
        useEqualHeights: true
    - CasaOS:
        icon: casaos.png
        href: "http://{{HOMEPAGE_VAR_THEDORNA_CASAOS}}"
        useEqualHeights: true
    - Kopia Dorna:
        icon: kopia.png
        href: "http://{{HOMEPAGE_VAR_THEDORNA_KOPIA}}" 
        useEqualHeights: true