# ~/docker/homepage/config/settings.yaml
title: "THE BRAIN // CORE_UNIT"
background: https://images.alphacoders.com/133/1338304.png
theme: dark
color: slate
cardBlur: sm
headerStyle: boxedWidgets
target: _self
#fullWidth: true

layout:
  Media:
    tab: Main
    style: row 
    columns: 3
  Office & Tools:
    tab: Main
    style: row 
    columns: 3
  Dev Stuff:
    header: false
    tab: Development
    columns: 2
  The Dorna:
    header: false
    tab: The Dorna
    columns: 1

quicklaunch:
  provider: custom
  url: https://www.ecosia.org/search?method=index&q=
  target: _self
  suggestionUrl: https://ac.ecosia.org/autocomplete?type=list&q=
  hideInternetSearch: false
  showSearchSuggestions: true

appearance:
  colors:
    gray:
      900: "#050505"
    slate:
      700: "rgba(20, 20, 35, 0.8)"
