- glances:
    url: {{HOMEPAGE_VAR_GLANCES_URL}}
    version: 4
    cpu: true
    mem: true
    cputemp: true
    uptime: true
    diskUnits: bytes
    expanded: true
    label: The Brain
    
- resources:
    label: Root
    disk:
      - /

- resources:
    label: SSD
    disk:
      - /mnt/SSD

- resources:
    label: Media Vault
    disk:
      - /mediavault

- resources:
    label: YT Backup
    disk:
      - /NAS2
      
- datetime:
    text_size: l
    format:
      dateStyle: short
      timeStyle: short
      hour12: false

- openmeteo:
    label: Cluj-Napoca
    latitude: {{HOMEPAGE_VAR_LATITUDE}}
    longitude: {{HOMEPAGE_VAR_LONGITUDE}}
    timezone: Europe/Bucharest
    units: metric
    cache: 5
